mongodb:
  host: localhost
  port: 27017
  authentication-database: admin
  database: configuration
  username: root
  password: password

minio:
  host: localhost
  port: 9000
  access_key: gl8rbGORHSpxmg1V
  secret_key: 8WphDMckYqRb29s43SzA4trsV2GgaQRc
